import time
from selenium import webdriver
from selenium import Service
from selenium.webdriver.common.by import By

servObj=Service("C:\Pycharm2023\webdriver\chromedriver")
driverChrome= webdriver.Chrome(service=servObj)
driverChrome.implicitly_wait(10)

driverChrome.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login")
driverChrome.maximize_window()

#To switch between diferents windows of browser we need know WindowsId (that pass as parameter to a method)
# WindowsId cant obtained through the DOM
# WindowsID are dynamics because those ids are automatically and randomly generated by the broser its self
# current_window_handle its a command than returns windowsId of single browser id
# window_handles will return windows ID's from multiple browser windows

# idWindows=driverChrome.current_window_handle
# print("ID: ", idWindows) #CDwindow-1E6C00C2F7CE91397A505666D343F62A (diferents ID)
#                          #CDwindow-05345437ABC333DE336B038585773E77

driverChrome.find_element(By.LINK_TEXT, value="OrangeHRM, Inc").click()
windowIds=driverChrome.window_handles

# Approach 1
# for i in range (len(windowIds)):
#     print(windowIds[i])
#
# print("title of parent windows: "+driverChrome.title)
# driverChrome.switch_to.window(windowIds[1]) #Child windows
# print("title of child windows: "+driverChrome.title)
# driverChrome.switch_to.window(windowIds[0]) #Parent windows

# Approach 2
# for WinId in windowIds:
#     driverChrome.switch_to.window(WinId)
#     print(driverChrome.title)

#Close specific window based on my choice (tittle page)
for WinId in windowIds:
    driverChrome.switch_to.window(WinId)
    if driverChrome.title=="OrangeHRM":
        driverChrome.close()

time.sleep(4)
# driverChrome.close()
driverChrome.quit()